usethis::use_package( "thinkr" )
usethis::use_package( "RSQLite" )
usethis::use_package( "DT" )

golem::add_module( name = "create_databases" ) # Module to create/delete databases
golem::add_module( name = "side_panel" )

golem::add_fct( "helpers" ) 
golem::add_utils( "helpers" )
golem::add_js_file( "script" )
golem::add_js_handler( "handlers" )
golem::add_css_file( "custom" )
usethis::use_data_raw( name = "my_dataset", open = FALSE ) 
usethis::use_test( "app" )
usethis::use_vignette("rsqliteadmin")
devtools::build_vignettes()
usethis::use_github()
usethis::use_travis()
usethis::use_appveyor()
rstudioapi::navigateToFile("dev/03_deploy.R")
